find_program(NVCC_DEVICE_QUERY "__nvcc_device_query")

if(NVCC_DEVICE_QUERY)
  execute_process(
    COMMAND ${NVCC_DEVICE_QUERY}
    OUTPUT_STRIP_TRAILING_WHITESPACE
    OUTPUT_VARIABLE NVCC_ARCH)
endif()

message(STATUS "CMAKE_CUDA_ARCHITECTURES: ${NVCC_ARCH}")
set(CMAKE_CUDA_ARCHITECTURES ${NVCC_ARCH})
